### ISSUE TITLE
gmap.gpd and gmap.ac.gpd do not work

### ISSUE THREAD

**Issue by juanb001** [QidiPeng/eQTLMAPT#2]
Hello,

I've had success  running the gmap() function without issues.

However, I have been unable to get the above functions to work properly. 

When I run gmap.gpd() using the same genotype, expression, etc. inputs as the gmap() function, I get this error:

[1] "call Pgpd"
Error in if (abs(x) < REALMIN) return(2^(-1074)) : 
  the condition has length > 1

Similarly, when I try to run the gmap.ac.gpd function, I get this error:

Error in svd(x, nu = 0, nv = k) : infinite or missing values in 'x'

I've double checked, and there are no NAs in my expression matrix.

For reference, I am running R 4.2.1

**Comment by stormlovetao** [comment]
Sorry for the late reply. We have fixed the bug. Please retry!

**Comment by juanb001** [comment]
Hello!

I tried re-installing eqtlmapt today and tried the gmap.gpd function. However, the same issue remains:

[1] "call Pgpd"
Error in if (abs(x) < REALMIN) { : the condition has length > 1


Any suggestions?
